# Generated by Django 4.2.3 on 2023-07-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'MANAGER'), (1, 'MEMBER')], null=True),
        ),
    ]
