# Generated by Django 4.2.3 on 2023-07-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0002_skill_proficiency_task_created_at_task_updated_at_and_more'),
        ('Auth', '0003_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(blank=True, to='TaskManager.skill'),
        ),
    ]
