# Generated by Django 4.2.3 on 2023-07-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0003_alter_task_options_task_skill_and_more'),
        ('Auth', '0004_alter_user_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='TaskManager.task'),
        ),
    ]
