# Generated by Django 4.2.3 on 2023-07-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_user_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'MANAGER'), (1, 'MEMBER')], default=1),
        ),
    ]
