# Generated by Django 4.2.3 on 2023-07-12 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0002_skill_proficiency_task_created_at_task_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['start_date']},
        ),
        migrations.AddField(
            model_name='task',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TaskManager.skill'),
        ),
        migrations.AlterField(
            model_name='task',
            name='effort_estimate',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(),
        ),
    ]
