# Generated by Django 4.2.3 on 2023-07-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0003_alter_task_options_task_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
