# Generated by Django 4.2.3 on 2023-07-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0004_alter_task_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='skill',
        ),
        migrations.AddField(
            model_name='task',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='TaskManager.skill'),
        ),
    ]
