

MIN_PROFICIENCY = 0.0
MAX_PROFICIENCY = 0.0

PROFICIENCY_MIN_RATING = 0.0
PROFICIENCY_MAX_RATING = 10.0
PROFICIENCY_NOT_WITHIN_RANGE = "Proficiency should be within {} and {}".format(PROFICIENCY_MIN_RATING, PROFICIENCY_MAX_RATING)

