version: "3"
services:

  crewer:
    image: docker.io/crewer/staffing:final
    container_name: crewer
    restart: unless-stopped
    volumes:
      - ./data:/usr/src/crewer/static/
    ports:
      - "8030:3000"
    env_file: crewer.env
  postgresdb:
    image: crewer:final_backup
    container_name: postgresdb
    restart: always
    ports:
      - "5433:5432"
    env_file: db.env
