version: "3"
services:

  crewer:
    image: thedoodler/crewer:server
    container_name: crewer
    restart: unless-stopped
    volumes:
      - ./data:/usr/src/crewer/static/
    ports:
      - "8090:3000"
    env_file: crewer.env
  postgresdb:
    image: thedoodler/crewer:pg_data
    container_name: postgresdb
    restart: always
    ports:
      - "5433:5432"
    env_file: db.env
