version: "3"
services:

  crewer:
    image: crewer:latest
    container_name: crewer
    restart: unless-stopped
    volumes:
      - ./data:/usr/src/crewer/static/
    ports:
      - "8080:3000"
    env_file: crewer.env

